server:
  port: 8070

accessTokenValiditySeconds: 60
spring:
  # 数据库配置
  datasource:
    database1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      hikari:
        #  连接池最大连接数: cpu核心数*2 + 硬盘数, 默认10 一个连接池一般来讲连接数在10-20个, 根据部署的应用程序数量可以推测出mysql的max_connections值
        maximum-pool-size: 15
        # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
        idle-timeout: 600000
        # 一个连接的生命时长（毫秒），超时并且没被使用则被释放（retired），缺省:30分钟。建议设置比数据库超时时长少30秒，參考MySQL wait_timeout參数（show variables like '%timeout%';）
        max-lifetime: 1800000
        # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException。 缺省:30秒
        connection-timeout: 30000
        connection-test-query: SELECT 1
    database2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      hikari:
        #  连接池最大连接数: cpu核心数*2 + 硬盘数, 默认10 一个连接池一般来讲连接数在10-20个, 根据部署的应用程序数量可以推测出mysql的max_connections值
        maximum-pool-size: 15
        # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
        idle-timeout: 600000
        # 一个连接的生命时长（毫秒），超时并且没被使用则被释放（retired），缺省:30分钟。建议设置比数据库超时时长少30秒，參考MySQL wait_timeout參数（show variables like '%timeout%';）
        max-lifetime: 1800000
        # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException。 缺省:30秒
        connection-timeout: 30000
        connection-test-query: SELECT 1

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG